Домашняя работа №1
mihail-jdanov/FocusStartHomeworks pull request #1
Opened 2020-10-16 19:00 UTC by mihail-jdanov

2020-10-17 11:28 UTC, korshunigor commented
Задание принято на проверку

2020-10-23 05:13 UTC, Jinfaa commented on Homework/CarsDataSource.swift
> +    var cars: [Car] = []
Для DataSource нужна функция записи в этот массив, и извлечения данных. Чтобы была соблюдена целостность массива и консистентность класса по работе с владемыми им данными. Модель CRUD

2020-10-23 05:13 UTC, Jinfaa commented on Homework/CarsDataSource.swift
> +    var cars: [Car] = []
в том числе и сортировка

2020-10-23 05:19 UTC, Jinfaa requested changes
В целом хорошо. Но хотелось бы чтобы ты доработал DataSource

2020-10-23 19:09 UTC, mihail-jdanov commented on Homework/CarsDataSource.swift
> +    var cars: [Car] = []
Внёс правки
https://github.com/mihail-jdanov/FocusStartHomeworks/commit/55d591f141d4de046193ac49f12526483001ecb3

2020-10-24 03:31 UTC, Jinfaa commented on Homework/CarsDataSource.swift
> +        if cars.contains(car) { return }
guard в таком случае нужно использовать. 
И давай сюда передавать каждое свойство и тут создавать Car

2020-10-24 03:32 UTC, Jinfaa requested changes
Еще одно небольшое замечание

2020-10-24 09:08 UTC, mihail-jdanov commented on Homework/CarsDataSource.swift
> +        if cars.contains(car) { return }
Поправил
https://github.com/mihail-jdanov/FocusStartHomeworks/commit/47011e528684bbdf0148430c17f865dffc9362ad

2020-10-25 07:40 UTC, Jinfaa approved these changes
Все хорошо, можно мержить

2020-10-25 09:28 UTC, merged