Домашняя работа №3
mihail-jdanov/FocusStartHomeworks pull request #3
Opened 2020-11-02 18:11 UTC by mihail-jdanov

Домашняя работа с тремя экранами и Tab Bar. Первый экран - лэйблы, кнопка и картинка в Stack View, второй - с лэйблами и картинкой (верстка с адаптацией под Size Class-ы), третий - два текстовых поля под логин и пароль и кнопка, меняющая положение при показе / скрытии клавиатуры.

2020-11-03 10:20 UTC, GkFoxes commented
Принял на проверку, передаю преподавателю!

2020-11-09 18:06 UTC, korshunigor commented
Задание принято на проверку

2020-11-13 22:04 UTC, korshunigor requested changes
Давай подфиксим имеющиеся замечания, затем посмотрим еще раз

2020-11-13 22:04 UTC, korshunigor commented on Homework3/Homework3/View Controllers/Third View Controller/ThirdView.swift
> +            of: safeAreaLayoutGuide, constant: -enterButtonDefaultBottomSpacing)
Тут отступ уехал в сторону + снова по несколько параметров на разных строках

2020-11-14 14:32 UTC, mihail-jdanov commented on Homework3/Homework3/Constants.swift
> +enum Spacings {
Поправил
https://github.com/mihail-jdanov/FocusStartHomeworks/commit/3e9ce52c8a77b5028ec33c1f6eda680426d63a68

2020-11-14 14:32 UTC, mihail-jdanov commented on Homework3/Homework3/Extensions/UIColor.swift
> +        let a, r, g, b: UInt64
Поправил
https://github.com/mihail-jdanov/FocusStartHomeworks/commit/3e9ce52c8a77b5028ec33c1f6eda680426d63a68

2020-11-14 14:32 UTC, mihail-jdanov commented on Homework3/Homework3/Extensions/UIView.swift
> +    func pin(_ firstAttribute: NSLayoutConstraint.Attribute, to secondAttribute: NSLayoutConstraint.Attribute = .notAnAttribute,
Поправил
https://github.com/mihail-jdanov/FocusStartHomeworks/commit/3e9ce52c8a77b5028ec33c1f6eda680426d63a68

2020-11-14 14:34 UTC, mihail-jdanov commented on Homework3/Homework3/Extensions/UIView.swift
> +        let constraint = NSLayoutConstraint(
<img width="497" alt="Снимок экрана 2020-11-14 в 21 23 25" src="https://user-images.githubusercontent.com/46405630/99149496-02a76300-26c1-11eb-9a32-f6f189194b8c.png">
Поправил, но мне не очень нравится это появившееся слева пустое место.
https://github.com/mihail-jdanov/FocusStartHomeworks/commit/3e9ce52c8a77b5028ec33c1f6eda680426d63a68

2020-11-14 14:35 UTC, mihail-jdanov commented on Homework3/Homework3/View Controllers/First View Controller/FirstView.swift
> +    func layoutViews() {
Поправил
https://github.com/mihail-jdanov/FocusStartHomeworks/commit/3e9ce52c8a77b5028ec33c1f6eda680426d63a68

2020-11-14 14:35 UTC, mihail-jdanov commented on Homework3/Homework3/View Controllers/First View Controller/FirstView.swift
> +    func layoutFirstLabel() {
Поправил

2020-11-14 14:36 UTC, mihail-jdanov commented on Homework3/Homework3/View Controllers/First View Controller/FirstView.swift
> +        let width: CGFloat = 100
Поправил
https://github.com/mihail-jdanov/FocusStartHomeworks/commit/3e9ce52c8a77b5028ec33c1f6eda680426d63a68

2020-11-14 14:36 UTC, mihail-jdanov commented on Homework3/Homework3/View Controllers/First View Controller/FirstView.swift
> +        stackView.addSubview(activityIndicator)
Поправил
https://github.com/mihail-jdanov/FocusStartHomeworks/commit/3e9ce52c8a77b5028ec33c1f6eda680426d63a68

2020-11-14 14:36 UTC, mihail-jdanov commented on Homework3/Homework3/View Controllers/Second View Controller/SecondView.swift
> +            traitCollection.verticalSizeClass != previousTraitCollection?.verticalSizeClass else { return }
Поправил
https://github.com/mihail-jdanov/FocusStartHomeworks/commit/3e9ce52c8a77b5028ec33c1f6eda680426d63a68

2020-11-14 14:37 UTC, mihail-jdanov commented on Homework3/Homework3/View Controllers/Third View Controller/ThirdView.swift
> +    private func keyboardWillShow(_ notification: NSNotification) {
Поправил
https://github.com/mihail-jdanov/FocusStartHomeworks/commit/3e9ce52c8a77b5028ec33c1f6eda680426d63a68

2020-11-14 14:37 UTC, mihail-jdanov commented on Homework3/Homework3/View Controllers/Third View Controller/ThirdView.swift
> +    private let enterButtonDefaultBottomSpacing = Spacings.standard
Поправил
https://github.com/mihail-jdanov/FocusStartHomeworks/commit/3e9ce52c8a77b5028ec33c1f6eda680426d63a68

2020-11-14 14:38 UTC, mihail-jdanov commented on Homework3/Homework3/View Controllers/Third View Controller/ThirdView.swift
> +            of: safeAreaLayoutGuide, constant: -enterButtonDefaultBottomSpacing)
Сделал по одному параметру на каждую строку
https://github.com/mihail-jdanov/FocusStartHomeworks/commit/3e9ce52c8a77b5028ec33c1f6eda680426d63a68

2020-11-14 20:06 UTC, korshunigor approved these changes
Есть не большое дополнение по форматированию, в остальном все ок

2020-11-14 20:06 UTC, korshunigor commented on Homework3/Homework3/View Controllers/Second View Controller/SecondView.swift
> +            else { return }
При расположении else на отдельной строе его лучше делать вровень с guard (форматирование с помощью Control + I собственно такой отступ и сделает, но это минор - правка на твое усмотрение)

2020-11-15 04:30 UTC, mihail-jdanov commented on Homework3/Homework3/View Controllers/Second View Controller/SecondView.swift
> +            else { return }
Поправил
https://github.com/mihail-jdanov/FocusStartHomeworks/commit/64fa9f3ee32bde16b99da319113e61af2b2722a9

2020-11-20 11:35 UTC, merged